/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Serial.h
 #	source generated by 4D Plugin Wizard
 #	Project : Serial
 #	author : miyako
 #	2022/02/04
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SERIAL_H
#define PLUGIN_SERIAL_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "4DPlugin-JSON.h"

#include <mutex>

void listenerInit(void);
void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

#if VERSIONMAC
#import "ORSSerialPort.h"
#import "ORSSerialPortManager.h"
@interface ORSSerialPortHelper : NSObject <ORSSerialPortDelegate>

@property(atomic, copy) NSString *callbackMethodName;
@property(atomic, copy) NSString *callbackMethodContext;

@end

@interface ORSSerialPortObserver : NSObject
{

}

- (void)serialPortsWereConnected:(NSNotification *)notification;
- (void)serialPortsWereDisconnected:(NSNotification *)notification;

@end

#endif

#pragma mark -

void SERIAL_GET_AVAILABLE_PORTS(PA_PluginParameters params);
void SERIAL_OPEN_PATH(PA_PluginParameters params);
void SERIAL_CLOSE_PATH(PA_PluginParameters params);
void SERIAL_SEND_DATA(PA_PluginParameters params);

#endif /* PLUGIN_SERIAL_H */
